spring:
  application:
    name: NpcResponse

    servlet:
      encoding:
        force-response: true
        charset: UTF-8

  ai:
    ollama:
      embedding:
        model: llama2

      chat:
        options:
          model: llama2

      base-url: http://localhost:11434
