FROM adoptopenjdk/openjdk17:jdk-17.0.5_10-alpine
WORKDIR /app
# TODO изучить Docker и написать Docker файл для Spring приложения (а потом и compose, он должен сначала запустить контейнер с нейросетью OILama, а уже потом и само приложение!)